name: flutter_graduation_nti
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4

  # State management
  provider: ^6.1.2

  # Local storage
  shared_preferences: ^2.2.2

  #  Localization 
  flutter_localizations:
    sdk: flutter
  intl: any

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  http: ^1.1.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - lib/assets/images/background.jpg


